# This config file is meant for settings that affect your whole blog, values which you are expected to set up once and rarely edit after that. If you find yourself editing this file very often, consider using Jekyll's data files feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/


# Site settings
# These are used to personalize your new site. If you look in the HTML files, you will see them accessed via {{ site.title }}, {{ site.email }}, and so on. You can create any custom variable you would like, and they will be accessible in the templates via {{ site.myvariable }}.

url:            "https://moab.news"
title:          Moab News
email:          carter@moab.news
tagline:        Weekday morning updates from Grand County, Utah
description:    News in your inbox every weekday morning with the latest out of Grand County, Utah
author:         carterpape

# Formatting settings

permalink:  pretty
timezone:   "America/Denver"
date_format: "%b. %-d, %Y"

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            authors: ["Carter Pape"]
            layout: "post"
            featured_image:
                same_as_social_image: true

kramdown:
    footnote_backlink: "⤴"


# Build settings

lsi:        true
livereload: true
open_url:   true

liquid:
    error_mode:         warn
    strict_variables:   false
    strict_filters:     false

sass:
    style: compressed

jekyll-minifier:
    compress_css: false

titles_from_headings:
    strip_title: true
    collections: true

# Exclude from processing.
# The following items will not be processed, by default. Any item listed under the `exclude:` key here will be automatically added to the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or their entries' file path in the `include:` list.

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - .gitignore
    - s3_website.yml
    - .env

jekyll_compose:
    default_front_matter:
        drafts:
            day_of_week:    "%%%%day"
            subtitle:       
            description:    
            image:          
        posts:
            day_of_week:    "%%%%day"
            subtitle:       
            description:    
            image:          
