#!/bin/zsh
set -e

script_path=$(realpath $0)
scripts_dir_path=$(dirname $script_path)
project_dir_path=$(dirname $scripts_dir_path)
site_path="$project_dir_path/_site"
posts_path="$project_dir_path/_posts"
post_assets_path="$project_dir_path/assets/posts"

dev () {
    bundle exec jekyll serve --incremental
}

test () {
    # check_names --print-on-fail
    # check_for_archived_pages
    JEKYLL_ENV="production" bundle exec jekyll build --incremental
    proof_html
    rclone sync \
        --checksum \
        --progress \
        --fast-list \
        --track-renames \
        --dry-run \
        $site_path \
        s3-for-moab-news:moab.news
}

push () {
    git pull
    git push
    # check_names --die-on-fail
    # archive_new_links
    JEKYLL_ENV="production" bundle exec jekyll build
    proof_html
    rclone sync \
        --checksum \
        --progress \
        --fast-list \
        --track-renames \
        $site_path \
        s3-for-moab-news:moab.news
    # set the caching headers on all files that need it with https://s3tools.org/s3cmd (maybe)
    # purge the cache of updated files
}

give_names () {
    $dir_path/scripts/give_names.rb
}

check_names () {
    $dir_path/scripts/check_names.rb $1
}

purge_htmlproofer_cache_of_internal_query_links() {
    gsed -i 's ,"\(/\|#\)[^"]*?[^"]*":{[^}]*}  g' "$project_dir_path/tmp/.htmlproofer/cache.log"
}

proof_html () {
    purge_htmlproofer_cache_of_internal_query_links()
    htmlproofer $site_path  \
        --internal_domains moab.news \
        --assume_extension \
        --enforce_https \
        --check_favicon \
        --check_html \
        --check_opengraph \
        --check_img_http \
        --report_invalid_tags \
        --report_missing_names \
        --report_eof_tags \
        --report_mismatched_tags \
        --timeframe 2d
}

subcommand="${1}" 
case ${subcommand} in 
    dev)
        dev
        ;;
    test)
        test
        ;;
    push)
        push
        ;;
    *)
        echo "`basename ${0}`: usage: dev | test | push" 
        exit 1
        ;; 
esac
